name: Build and Publish

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build (Node.js 12.x)
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: |
          npm ci
          npm run build
      - name: Publish Artifacts # For use in other jobs in this workflow
        uses: actions/upload-artifact@v2
        with:
          name: simple-env-dist
          path: dist 

  publish:
    name: Publish to NPM
#     if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Get Artifact
        uses: actions/download-artifact@v2
        with:
          name: simple-env-dist
          path: dist
        
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}
